### ISSUE TITLE
iCloud ... 😡 

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#439]
Trying to Download my Photos from iCloud because they are taking up space ...
![image](https://user-images.githubusercontent.com/194400/34132040-04c72352-e446-11e7-8f88-434a2bc1eeff.png)

![image](https://user-images.githubusercontent.com/194400/34132011-ed2ad284-e445-11e7-81be-d3eb62a6e70b.png)

![icloud-photos-unavailable](https://user-images.githubusercontent.com/194400/34131275-dfd43254-e442-11e7-912b-dcffd63d1073.png)

## Todo

+ [ ] Download all previous iPhoto images from iCloud
+ [ ] Erase all images from iCloud
+ [ ] Only use iCloud for the bare minimum (_e.g: Find-my-iPhone_)

**Comment by nelsonic** [comment]
First thing you see when you open developer tools is: "_We are hiring the sharpest minds_..."
![image](https://user-images.githubusercontent.com/194400/34131861-470cd154-e445-11e7-81dd-18f1a68b6428.png)
No thank you!
I'm just trying to download my photos so that I can "Quit You" ...!

Notice how they embed the iCloud Photos "App" in an iFrame:
![image](https://user-images.githubusercontent.com/194400/34131641-5b93ed34-e444-11e7-962a-5cbe4f1a2945.png)

This way it cannot be "targetted" using JavaScript because of 

The id of the `<iframe>` is: sc4346
so this works:
```js
var iframe = document.getElementById('sc4346');
```
https://stackoverflow.com/questions/926916/how-to-get-the-bodys-content-of-an-iframe-in-javascript

but sadly this does not:
```
document.getElementById('sc4346').contentDocument.getElementById('p2-base-flow-grid-item-view')
```
https://stackoverflow.com/questions/20911333/get-element-from-iframe-and-click-it

**Comment by nelsonic** [comment]
Downloading:
![image](https://user-images.githubusercontent.com/194400/34132095-39c8899c-e446-11e7-82be-3d1c3bd03e9b.png)

Let's see if I run out of space (_again_) before the Photo download finishes ...
![image](https://user-images.githubusercontent.com/194400/34132230-c197a6c8-e446-11e7-9861-fbc07c9d2a83.png)
