### ISSUE TITLE
How to Edit .doc / .docx (Microsoft Word) Documents Without the Program

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#808]
# Context

My Dad is a retired Journalist > Editor > Publisher turned Historian/Author who spends his life reading and writing. 📚 ✍️ 
While my parents were visiting us in [Braga](https://github.com/dwyl/home) last week, he was proof-reading a book **printed** from a **`.docx` file**:

![dad-hand-editing](https://user-images.githubusercontent.com/194400/89710379-38c69f80-d97a-11ea-9922-ba20b63b5e21.jpg)

In this photo, you can just about see the spiral-bound book being used as a _support_ for the A4 white paper he is using to write his notes. He read, highlighted and annotated the printed book comprehensively and now wants to integrate those changes back into the original `.docx` Word Doc. 

This _cropped_ photo in from a slightly different angle shows the blue spiral slightly better:

![dad-spiral-book](https://user-images.githubusercontent.com/194400/89714009-84397780-d993-11ea-9565-6c3a33b87e76.jpg)

> **Writing by _hand_**...? My Dad prefers to write by _hand_ rather than use a computer. 
_Many_ writers prefer to "think on paper" than use screens that can be distracting. 
I _agree_ that writing on paper helps me to _think_; that's why I still carry/use a Moleskine paper notebook. 
But having learned how to touch-type as kid and, and having practiced over the decades including several last-minute deadline speed-typing sessions 🙄, I can compose **3-5 times faster** on a computer so I end up defaulting to "writing" on my Laptop most of the time ... which is why my choice of Laptop is so important to me: https://github.com/nelsonic/nelsonic.github.io/issues/371#issuecomment-463151626 ... I gave my Dad a brand new HP Laptop with Windows 10 Pro a couple of years ago to replace his _ancient_ Toshiba (Windows XP) and _prehistoric_ Desktop (Windows Vista!!) but he only uses it as his "photo viewer" ... not as a ["daily driver"](https://en.wiktionary.org/wiki/daily_driver) ... the age of his "main" (Desktop) computer will be relevant below. ⏳ 
 

> **Side Note**: I have **zero** "regrets" buying the [**iPhone 11**](https://github.com/nelsonic/nelsonic.github.io/issues/31#issuecomment-625860943), the camera is _superb_ and ultrawide lens is _worth_ it!

# _Request_

This morning, Dad emailed me to ask if I can help him to integrate his corrections into the original `.docx` file:

![image](https://user-images.githubusercontent.com/194400/89712175-08393280-d987-11ea-8786-49d10bc86054.png)

> **Note**: I used **Google Translate** to convert the original Portuguese email to English for this post. Google hasn't done a very good job of Grammar/Syntax, but hopefully you get the idea. He wants help editing the attached `.docx` file. 

One of the _many_ advantages of having IT skills is that you get to help your loved ones save time in their tasks ...
Obviously I would _prefer_ it if my Dad worked on his _Googling_ skills and figured it out himself through "_clicksploration_", however like most people that grew up _without_ computers, he does not _immediately_ ***ask Google*** when he has a question. 

e.g: https://www.google.com/search?q=how+to+edit+docx+file+online+without+word
![image](https://user-images.githubusercontent.com/194400/89710305-afaf6880-d979-11ea-87a2-bd4362a4902e.png)

# Todo

+ [x] Explain with screenshots how to **edit** a **`.docx`** file sent as an email attachment in **Google Docs**
+ [x] Include _explanation_ of "***track changes***" and "***suggesting***" mode.
+ [x] Show how to ***share*** the URL of the Goolge Doc so that the co-authors/editors can _collaborate_ on the Doc.
+ [x] Show how to ***export*** the Google Doc back to **.docx`** so that it can be returned as an attachment 🤦

**Comment by nelsonic** [comment]
**Note**: if any of the images below are too small to read, click on the image to see a bigger version.
And if anything in this guide does not work in your [Web Browser](https://en.wikipedia.org/wiki/Web_browser), please consider using a more recent computer with an up-to-date [Operating System](https://en.wikipedia.org/wiki/Operating_system) as some features might only work in the latest [Google Chrome Browser](https://en.wikipedia.org/wiki/Google_Chrome).


# 1. _Edit_ the Attachment by Clicking the "Edit" Button


When you _hover_ over an attachment in Gmail 3 buttons appear:
<img width="200" alt="gmail-attachement-actions-3-buttons" src="https://user-images.githubusercontent.com/194400/89715021-9ec31f00-d99a-11ea-9861-da5f014a72e9.png">

1. Download the attachment
2. Add the attachment to Google Drive
3. ***Edit*** the document

If you click the **Edit** icon, it will open the Attachment as a Document that you can _edit_, e.g:
![image](https://user-images.githubusercontent.com/194400/89715080-1f821b00-d99b-11ea-8aca-db29489f3a1f.png)

# 2. _Suggesting_ Mode

If you are editing someone else's manuscript or document, it can be useful to use "suggesting" mode so that the author/owner of the document can both _see_ the changes you have made and _decide_ if they want to _apply_ them.

In the top right of the Google Docs menu, you will see a **_pencil_ icon**. 

<img width="1187" alt="google-docs-editing-mode" src="https://user-images.githubusercontent.com/194400/89715131-a505cb00-d99b-11ea-8028-2465a53e068e.png">

If you ***hover*** over the **edit** button/icon with your mouse cursor, it will reveal which "mode" you are in.

If you ***click*** the **edit** button (dropdown) it will allow you to select "**suggesting**" mode.

<img width="282" alt="google-docs-editing-suggestions" src="https://user-images.githubusercontent.com/194400/89715163-e4ccb280-d99b-11ea-8e6f-78e7a924c137.png">

The icon in the menu will change to the following to indicate you are "suggesting" mode:

![image](https://user-images.githubusercontent.com/194400/89715178-f8781900-d99b-11ea-9756-259cf05ef50d.png)

Hover over the icon to confirm that you are in "suggesting" mode:

![image](https://user-images.githubusercontent.com/194400/89715321-cb783600-d99c-11ea-8eea-2e912d79df1c.png)

If I then _edit_ the document the changes I make will appear in **green** with a bubble in the right margin:

![image](https://user-images.githubusercontent.com/194400/89715375-3aee2580-d99d-11ea-9008-4c5f2cb4a0ca.png)

The _owner_ of the Google Document can chose which suggestions to ***accept*** or ***reject***:

![image](https://user-images.githubusercontent.com/194400/89715467-a33d0700-d99d-11ea-8e6e-5811a40e5376.png)

![image](https://user-images.githubusercontent.com/194400/89715498-d4b5d280-d99d-11ea-8ba6-02b62f2c8f6a.png)

For example: if the **author/owner** of the document was to _accept_ the first and last suggestions but ***reject*** the middle one the subtitle would go from:

### “Birth of a legendary unit and the life and times of Major Alvaro Manuel Alves Cardoso” 

to:

### “The birth of a legendary unit and the life of Major Alvaro Manuel Alves Cardoso” 

This is a demonstration of editing the the quote on the first page for improved grammar and spelling:

![image](https://user-images.githubusercontent.com/194400/89715573-5c034600-d99e-11ea-85d1-ac74bd759e71.png)

# 3. _Share_ The Document with Collaborators

In the Top-right of the Google Docs Menu there is a "***Share***" button:

<img width="1303" alt="google-docs-share-button" src="https://user-images.githubusercontent.com/194400/89715961-5e1ad400-d9a1-11ea-9694-105cb4ce8e20.png">

Clicking this button allows you to share the Google Document with other people ("collaborators") by email.

> **Note**: this is not going to send the document as an _attachment_, this is sharing the _same_ document so that everyone can ***collaborate*** on the editing and get the book written _faster_. 

You will see the "Sharing" window (pop up) over the document:

<img width="1236" alt="google-docs-share-dialog" src="https://user-images.githubusercontent.com/194400/89719487-c3ca8880-d9c0-11ea-8aac-06d444b643e0.png">

Here you can share the Google Doc Document with your friends/colleagues/co-authors using their email address.
Once you have input their email address, click the "**Done**" button and they will receive an email inviting them to edit.

> **Note**: you can also chose to make the document ***`public`*** so that _anyone_ can read it, but this is not relevant to the book you are currently editing, so I have not included these instructions.

# 4. Download the Document so you can Send it as an Attachment

_Finally_ once you have performed all your editing, if you prefer to send the document as an attachment (_instead of sharing it with your co-oauthors following the steps in part 3 above_), you can simply download it send it as an attachment the same way that you received it:

<img width="1236" alt="google-docs-download-docx" src="https://user-images.githubusercontent.com/194400/89719627-22dccd00-d9c2-11ea-85d0-dd2099218676.png">

**Comment by nelsonic** [comment]
Replied:
![image](https://user-images.githubusercontent.com/194400/89719935-3c334880-d9c5-11ea-812b-5236b52373a9.png)

**Comment by nelsonic** [comment]
Closing as resolved. ✅
