### ISSUE TITLE
Reset MacBook Pro 15" TouchBar and Prep for Mobile Dev

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#815]
# Context

in 2018 I invested in a MacBook Pro 15" TouchBar _specifically_ for video editing: https://github.com/dwyl/video/issues/55#issuecomment-445800176
Sadly, the person I lent that Laptop to used it for _watching_ videos (Neflix, etc.) but not for _creating_/_editing_ video. 🤦 
More than a year after they received the MacBook Pro they hadn't made _any_ progress despite having the Davinci Resolve course https://github.com/dwyl/video/issues/53 and plenty of source content they could craft into a travel highlights video: [Around-the-World#2](https://github.com/edwardcodes/Around-the-World/issues/2#issuecomment-428503472)
I learned a _very_ valuable lesson from that experience which is the subject of another issue/post ... 💭 
The point is that the person in question decided they didn't "like" content creation ... (_more like they didn't like the **discomfort** of being a beginner and having to learn something from scratch_) so they returned the laptop and I now have it and can re-purpose it. Their loss. 

The laptop is _perfect_ for Video Editing as it has a Radeon Pro 555 Graphics Card with 2GB GDDR5 Memory.
But the specs also make it _perfect_ for Mobile App development which is where I will be focussing for the next 3-6 months.

# Todo

+ [x] _Clean_ the laptop (externally) 
+ [x] Reset to factory settings
+ [x] Update MacOS to Catalina (stable)
+ [x] Pair it with an _external_ Mac ("Magic") Keyboard and Track Pad
+ [x] Setup dedicated "Work" Desk for mobile App Dev (Client Project) 
+ [x] Refresh RN knowledge: https://github.com/dwyl/learn-react-native/issues/3

**Comment by nelsonic** [comment]
Fully Setup. ✅ 
Sadly there are a few keys sticking ... 🤦 
So I have to use it with an external keyboard ... ⌨️

**Comment by nelsonic** [comment]
Black Screen of Death on MacBook Pro 15 Touchbar ... 😞 
Trying this: https://ioshacker.com/how-to/macbook-pro-touch-bar-stuck-black-screen-esc-showing-fix

**Comment by nelsonic** [comment]
Sadly the `NVRAM` Reset didn't work ... 😞 
So trying an SMC Reset: https://support.apple.com/en-gb/HT201295 🤞

**Comment by nelsonic** [comment]
No luck with SMC reset ...
Going to try and boot into safe mode: https://www.applegazette.com/mac/macbook-pro-screen-goes-black/

**Comment by nelsonic** [comment]
Sadly the MacBook Pro 15 Screen is ***Dead***. 
I took it to the local (Authorized) Apple Store and the repair quote is **836,69€**:

![image](https://user-images.githubusercontent.com/194400/100025611-09c92200-2de1-11eb-9fd4-3c24fc0dc382.png)

This is utterly ridiculous as it's nearly the price of a **decent `new` laptop**! 
So instead of burning this cash on replacing the screen, I'm going to use it plugged into a monitor.

**Comment by nelsonic** [comment]
Apparently, there's a thing called "Closed-Display Mode" which means you can use your MacBook Pro that has a broken screen in a stand: https://support.apple.com/en-us/HT202351

via: https://www.twelvesouth.com/products/bookarc-macbook
![image](https://user-images.githubusercontent.com/194400/131256008-7962faa7-0fb8-4122-97e0-8b153e260efc.png)

Going to try it with the external Samsung display.

Thinking of getting one of these as a "replacement screen":
https://www.pcdiga.com/monitor-asus-zenscreen-mb16ace-ips-15-6-fhd-16-9-60hz-90lm0381-b04170
![image](https://user-images.githubusercontent.com/194400/131255883-059a96eb-f5fc-4038-b457-c7c868192d04.png)
