### ISSUE TITLE
Travel Checklist

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#907]
Making my travel checklist public so I can share it.

- [ ] Large backpack as hold luggage 🧳 
- [ ] Small backpack as plane bag and day (laptop) bag. 🎒 
- [ ] Passport 🛂
- [ ] Identity Card 🪪 
- [ ] Driving License 🪪
- [ ] Refillable water bottle 💧 

# Tech + Work

- [x] UK Travel Adapters 🇬🇧 (+1 spare)
- [ ] USB Charger for Hotel 🏨 
- [ ] USB Charger for Laptop @ office 💻 
- [ ] Laptop 💻 in carry case (charged!)
- [ ] MX master 3s Mouse 🐁 (in carry case)
- [ ] iPad (with downloaded documentaries + taking notes) ⌨️
- [ ] Kindle (for reading one-handed) 📕 
- [ ] Paper Book (for reading without screens!) 📖 
- [ ] _Paper_ Notebook 
  - [ ] Pens 🖊️ 
- [ ] GoPro (charged!) 📷 
  - [ ] spare battery 🔋 
- [ ] _Spare_ iPhone as backup
- [ ] Spare `5000mAh` battery to charge phone with USB C cable

# Clothes

- [ ] 5 work shirts 👔 (the hotel has laundry) 🧺 
  - [ ] Cufflinks
  - [ ] 2 Ties (blue and red)
- [ ] 2 x Work trousers 👖 
- [ ] Smart Casual Blazer
- [ ] 1 x Jeans 👖 
- [ ] 5 black T-shirts 👕 
- [ ] 2 pairs casual shorts 🩳 
- [ ] 10 pairs of boxers 🩲 
- [ ] 10 pairs of socks 🧦
- [ ] 5 pairs of trainer socks 🧦 (spares!)
- [ ] Work shoes 👞 (smart casual)
- [ ] Comfortable shoes 👟 (airports + after work)
- [ ] Swimsuit 🩳 
- [ ] Flip flops 🩴 
- [ ] swim cap 🏊‍♂️ 
- [ ] goggles 🥽 
- [ ] eye-mask for sleeping on plane 👓 
- [ ] Sunglasses 😎 
- [ ] Hat 🧢 

# Toiletries

- [ ] Toothbrush 🪥 
- [ ] Toothpaste ✨ 
- [ ] Floss 🦷 
- [ ] Plasters 🩹 
- [ ] Travel Swiss Army Knife 🇨🇭(in travel wallet)
- [ ] Deodorant (rollon) 
- [ ] Deo Spray in hold luggage
- [x] Small shower gel (they will have it free at the Hotel...)
